### PR TITLE
Added check for user's connection to the internet

### PR DESCRIPTION
**Pull request by VirxEC**
I've tested this - it correctly identifies when a user is online or offline.

This pings https://rlbot.org/ once, and looks for 'Lost = 0' in the ping command's output.

Fixes RLBot/RLBot#530

### CODE REVIEW

**Review by tarehart — COMMENTED** [review]
Looks good! Could we use something besides rlbot.org though, like google.com? I'm worried rlbot.org will be less reliable.

Based on the answers here , you could maybe redirect to nul rather than using a temp file, and simplify in other ways: https://stackoverflow.com/questions/6357515/batch-files-using-ping-to-test-network-connectivity/6357629

**Comment by VirxEC** [comment]
This should work - theoretically. I'll test it in a bit.

**Comment by VirxEC** [comment]
I tested the new commit, and it does properly work

**Review by tarehart — APPROVED** [review]
Thanks Virx!

**Comment by VirxEC** [comment]
What's that timing...

**Comment by VirxEC** [comment]
Well, it works, and I tested that, too

**Pull request merged**
