### PR TITLE
Update the packet more often

### PR DESCRIPTION
**Pull request by martmists**
This will improve accuracy in overlay

### CODE REVIEW

**Comment by IamEld3st** [comment]
Is this okay to merge?

**Comment by tarehart** [comment]
You're calling from overlay.html to python at 60Hz which was a CPU killer for me. I reduced that frequency dramatically to make the overlay a better citizen while I was streaming. We should probably find the right frequency for that expensive call, and do these updates at a matching frequency because even though it's fairly cheap, there's no point in exceeding the other rate, I think.

**Comment by IamEld3st** [comment]
At this moment I am considering switching this the other way around... aka create JS "interface" that can also be called from the python side... add events like on goal on kickoff on end JS events that get called from python side.
Hopefully this would make it easier on the cpu?

**Comment by tarehart** [comment]
Yeah, that's a good idea!

**Comment by martmists** [comment]
Odd, I had no issues at all with a higher refresh rate

**Comment by IamEld3st** [comment]
Currently merging... Issue will be fixed in an incoming PR...

**Pull request merged**
