### PR TITLE
100% Custom Python Install

### PR DESCRIPTION
**Pull request by VirxEC**
Updated the GUI screenshot
Verbose changes

RefreshEnv.cmd is no longer needed, as we're no longer relying on PATH.
We're now using Python 3.7.9 instead of 3.7.7.
We're no longer using the Python installer, and instead just unzipping the files. (This is due to a 'feature' that prevents Python from being installed multiple times on a machine.)
Due to CMD not being able to unzip files without 3rd party tools like 7Zip or WinRar, PowerShell is used.
Once Python is extracted, if we detect a pre-existing `venv` folder, then we edit `pyvenv.cfg` to instead use our new Python installation.

If you want to raw Python executable, do `%LocalAppData%\RLBotGUIX\Python37\python.exe` instead of `python` or `python3`.
If you want the packages too, then do `call %LocalAppData%\RLBotGUIX\venv\Scripts\activate.bat` and then use `python` like normal.

### CODE REVIEW

**Review by tarehart — COMMENTED** [review]
Looks very good! I won't have a chance to test tonight actually, will need to test tomorrow. Is the zip file downloaded directly from python.org?

**Comment by VirxEC** [comment]
No. What I did was I uninstalled my python, which let me install python in a custom location. I took the files from the custom location and zipped them, with no modifications. I then deleted those files and when to test if I could unzip the files in the proper location. I did this because the embedded zip on python.org doesn't include tcl/tk (which means to tkinter)

**Comment by VirxEC** [comment]
Apparently the parentheses were causing issues because they needed to be escaped. Fixed.

**Review by tarehart — APPROVED** [review]
I tested this and it worked quite nicely! I went ahead and remade the zip file so people have fewer people they need to trust.

Thanks for figuring this out Virx, I think this could make installations much more reliable.

**Pull request merged**
