### PR TITLE
Switching from material design to bootstrap.

### PR DESCRIPTION
**Pull request by tarehart**
Also:
- Fixing a bug where selections in the appearance editor unexpectedly blank out
- Improving the way we compose vue components so they can be debugged more easily
- Improving the python package installer

I've tested botpack download, python package install, new bot creation, folder settings, sandbox. Everything appears to be working.

image

### CODE REVIEW

**Comment by ViliamVadocz** [comment]
I played around with the gui for a while and these are my notes. Most of them are minor visual adjustments that I would like to see, but I did find a few bugs too.

The logo is too low:
image

Header has unnecessary margin on the left and right:
image

Hovering over a pressed button still changes the background to the original gray even though the text is now white, making it unreadable:
image

The warning screams at you visually. Maybe making the bots and script backgrounds lighter could help?
image

Scripts are not correctly hidden when searching:
image

Strange colouring on the radio button when pressed:
image

This highlight stays there (until you click again) after you remove a bot if another one takes its place:
image

In the appearance editor, pressing here selects the dropdown to the right:
image

When trying to show a the car through the appearance editor I get this error in the console, even though I have state setting enabled.
`Ignoring state setting attempt because it's disabled!`
image

This gui does not seem to install RLUtilities by default, causing Snek to not work:
`ModuleNotFoundError: No module named 'RLUtilities'`

On successful install of a package this window pops up. It looks very strange.
I don't think it needs two bars. Maybe the name could be moved up and the bottom bar would be removed or the X would be moved down and the top bar should be made smaller / removed.
image

After verifying that state setting did indeed work, I tried the showroom again and it worked. Then I left the match and tried again and got the same error: `Ignoring state setting attempt because it's disabled!`

**Comment by tarehart** [comment]
Good suggestions! Fixed everything I think except for:
- highlighting fields when clicking on label (intended behavior in bootstrap)
- X button outline remaining
- Coloring of team selector radio button (it's just semi transparent)

I'm not planning on fixing those right now.

**Comment by ViliamVadocz** [comment]
Happy to see it 👍

I think the only thing you missed that you didn't mention was that searching doesn't properly hide scripts. I can make an issue once this is merged, since right now it's not that big of a deal with only four scripts.

Another bug similar to the X button outline appears around the warnings if you decline the installation.
image

**Comment by tarehart** [comment]
Good point, fixed the searching. I'm happy with it now

**Pull request merged**
