### PR TITLE
Tags

### PR DESCRIPTION
**Pull request by Darxeal**
Do not merge this until https://github.com/RLBot/RLBot/pull/557 has been **deployed**. BotPack PR coming soon.

Implements #155, seperates bots into categories using predefined tags.

image

The definition of the categories can be found in `rlbot_gui/gui/js/categories.js`.
- All
  - displays all bots and scripts
  - doesn't have any sub-categories, but has a search field
    image
- Standard
  - Bots for 1v1 - `1v1`
  - Bots with teamplay - `teamplay`
  - Goalie bots - `goalie`
- Extra modes
  - Hoops - `hoops`
  - Dropshot - `dropshot`
  - Snow Day - `snow-day`
  - Rumble - `rumble`
  - Spike Rush - `spike-rush`
  - Heatseeker - `heatseeker`
  - scripts can also have these tags
- Special bots/scripts
  image
  - bots with a `memebot` tag are displayed on the top row
  - on the bottom, scripts and bots with `enables-something` paired with `requires-something`/`supports-something` are displayed in a way, best explained with a picture:
    image
    to explain some edge cases:
    - since Laserboi only supports-twitch, it doesnt require it, its also shown on the "independent scripts" row
    - SideSwipe enables, but it doesnt have any bot that supports it yet, so its also shown on that row
  - to make it clear what the bottom rows mean, the bots/script on the right are disabled if the script on the left isnt turned on, and there is a tooltip on the arrow

More changes:
- changed the behaviour of the Human type - now if its on one of the teams, it disappears from the bot pool, so it can only be in one place at the same time
- Human is now always the first in the pool (if visible), followed by psyonix bots (only in the All category), followed by other bots
- on a fresh install, blue team already has the Human placed in it
- changed default "add on click" team to orange, it makes sense with the previous change

Codebase related changes:
- refactored bot/script cards into their own components, both extending runnable-card
- added [VueX](https://vuex.vuejs.org/), so we don't have to propagate events through so many components

Feel free to have feedback, for the categories, their names, tag names, UI, etc.

### CODE REVIEW

**Comment by VirxEC** [comment]
looks good to me - waiting for the rlbot pr to be deployed.

**Comment by NicEastvillage** [comment]
Why is the search bar not always shown?

The UI of "Special bots/scripts" is still gonna be super confusing for new users. I wonder if we should add a small header to separate things. Sketch:
billede

**Comment by Darxeal** [comment]
> Why is the search bar not always shown?

To reduce UI clutter, I figured it's only needed when there's a lot of bots. I can put it in other tabs as well if you guys want, but to make it work with the script dependencies, there's some more work needed (it should probably hide/show entire rows)

> The UI of "Special bots/scripts" is still gonna be super confusing for new users. I wonder if we should add a small header to separate things. Sketch:

I think that looks good, but it takes up a lot of space vertically. Another option is to separate the 3 things onto different tabs. I'm not sure what's the best option 🤷

**Comment by VirxEC** [comment]
Get we get the search bar for the Standard tab too? I do agree with what Darx said, but I also think that that tab has a lot of bots

**Comment by VirxEC** [comment]
Or maybe not? that might be a bit much in the ui... maybe just the all tab is fine... ak

**Comment by NicEastvillage** [comment]
I like the search bar. I think we should keep it.

> it takes up a lot of space vertically

I am not too concerned about this if it makes it easier to understand.

**Comment by VirxEC** [comment]
maybe just put the search bar back to where it was before

**Comment by Darxeal** [comment]
Added search field to the tabs with a lot of bots - _Bots for 1v1_ and _Bots with teamplay_

Added headers as per East's suggestion
image

**Comment by VirxEC** [comment]
Can you also update the screenshot in readme? Or I could do that once this is deployed in another PR as I know I have a full RLBot install.

**Comment by Darxeal** [comment]
Is this viable? Warnings are okay imo, it is a feature after all
image

**Comment by VirxEC** [comment]
Sure, that doable

**Comment by NicEastvillage** [comment]
I can see that you hardcoded when the search bar is shown, which seems reasonable if the GUI only show RLBotPack bots. But then there's people like me with tons for bots because I have run multiple tournaments. I end up with many bots in multiple of the categories. I would like the search bar everywhere - or, as an compromise, whenever there is more than 10(?) bots in a category.

**Comment by Darxeal** [comment]
> I end up with many bots in multiple of the categories

I would argue that most bots outside of the botpack won't have any tags, so you'll have to use the All category anyway. But I added the search field to all the tabs. The dependencies needed a special behavior - the row is hidden only if none of the bots/scripts pass the filter.

**Comment by NicEastvillage** [comment]
Sounds great.

**Review by NicEastvillage — APPROVED** [review]

**Review by VirxEC — APPROVED** [review]
looks good!

**Pull request merged**
